function [imp_fh_big, imp_fh_small, imp_fh_micro] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [IMP_FH_BIG, IMP_FH_SMALL, IMP_FH_MICRO] = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as column vectors.
%
%  [IMP_FH_BIG, IMP_FH_SMALL, IMP_FH_MICRO] = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [imp_fh_big, imp_fh_small, imp_fh_micro] = importfile("D:\МГТУ аспа\matlab_microcircultaion\Modelling\Анатомическая модель_RPG3.txt", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Mar-2025 09:51:41

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "imp_fh_big", "imp_fh_small", "imp_fh_micro", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22"];
opts.SelectedVariableNames = ["imp_fh_big", "imp_fh_small", "imp_fh_micro"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
imp_fh_big = tbl.imp_fh_big;
imp_fh_small = tbl.imp_fh_small;
imp_fh_micro = tbl.imp_fh_micro;
end